plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  # TODO: This is a dependency of the Prettier "next" branch. Hopefully this
  # won't be required on the released version.
  "@angular/compiler@*":
    peerDependenciesMeta:
      tslib:
        optional: true
